# Make file for Website Reporting application
# Software Engineering CS 441



all: 
	g++ -o main Commandline_UI.cpp ConnectionManager.cpp DataRequestForm.cpp Model.cpp UserAccount.cpp WebsiteReporting.cpp databaseConnection.cpp jsoncpp.cpp textFileConnection.cpp -w -lsqlite3

       
